# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taskmanager
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btaskmanager\x12\x0btaskmanager\"%\n\x0e\x41\x64\x64TaskRequest\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\".\n\x0f\x41\x64\x64TaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t\"\x12\n\x10ListTasksRequest\"5\n\x11ListTasksResponse\x12 \n\x05tasks\x18\x01 \x03(\x0b\x32\x11.taskmanager.Task\":\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\x32\x9f\x01\n\x0bTaskService\x12\x44\n\x07\x41\x64\x64Task\x12\x1b.taskmanager.AddTaskRequest\x1a\x1c.taskmanager.AddTaskResponse\x12J\n\tListTasks\x12\x1d.taskmanager.ListTasksRequest\x1a\x1e.taskmanager.ListTasksResponseb\x06proto3')



_ADDTASKREQUEST = DESCRIPTOR.message_types_by_name['AddTaskRequest']
_ADDTASKRESPONSE = DESCRIPTOR.message_types_by_name['AddTaskResponse']
_LISTTASKSREQUEST = DESCRIPTOR.message_types_by_name['ListTasksRequest']
_LISTTASKSRESPONSE = DESCRIPTOR.message_types_by_name['ListTasksResponse']
_TASK = DESCRIPTOR.message_types_by_name['Task']
AddTaskRequest = _reflection.GeneratedProtocolMessageType('AddTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDTASKREQUEST,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.AddTaskRequest)
  })
_sym_db.RegisterMessage(AddTaskRequest)

AddTaskResponse = _reflection.GeneratedProtocolMessageType('AddTaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDTASKRESPONSE,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.AddTaskResponse)
  })
_sym_db.RegisterMessage(AddTaskResponse)

ListTasksRequest = _reflection.GeneratedProtocolMessageType('ListTasksRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTTASKSREQUEST,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.ListTasksRequest)
  })
_sym_db.RegisterMessage(ListTasksRequest)

ListTasksResponse = _reflection.GeneratedProtocolMessageType('ListTasksResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTTASKSRESPONSE,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.ListTasksResponse)
  })
_sym_db.RegisterMessage(ListTasksResponse)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.Task)
  })
_sym_db.RegisterMessage(Task)

_TASKSERVICE = DESCRIPTOR.services_by_name['TaskService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDTASKREQUEST._serialized_start=28
  _ADDTASKREQUEST._serialized_end=65
  _ADDTASKRESPONSE._serialized_start=67
  _ADDTASKRESPONSE._serialized_end=113
  _LISTTASKSREQUEST._serialized_start=115
  _LISTTASKSREQUEST._serialized_end=133
  _LISTTASKSRESPONSE._serialized_start=135
  _LISTTASKSRESPONSE._serialized_end=188
  _TASK._serialized_start=190
  _TASK._serialized_end=248
  _TASKSERVICE._serialized_start=251
  _TASKSERVICE._serialized_end=410
# @@protoc_insertion_point(module_scope)
