# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taskmanager
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btaskmanager\x12\x0btaskmanager\"\x1b\n\x19MoneyFlowClassiqueRequest\"+\n\x1aMoneyFlowClassiqueResponse\x12\r\n\x05value\x18\x01 \x01(\x02\"\x19\n\x17MoneyFlowTemporeRequest\")\n\x18MoneyFlowTemporeResponse\x12\r\n\x05value\x18\x01 \x01(\x02\"\x12\n\x10RendementRequest\"\"\n\x11RendementResponse\x12\r\n\x05value\x18\x01 \x01(\x02\"\r\n\x0bVwapRequest\"\x1d\n\x0cVwapResponse\x12\r\n\x05value\x18\x01 \x01(\x02\"\r\n\x0bTwapRequest\"\x1d\n\x0cTwapResponse\x12\r\n\x05value\x18\x01 \x01(\x02\x32\x9b\x03\n\x0bTaskService\x12\x65\n\x12MoneyFlowClassique\x12&.taskmanager.MoneyFlowClassiqueRequest\x1a\'.taskmanager.MoneyFlowClassiqueResponse\x12_\n\x10MoneyFlowTempore\x12$.taskmanager.MoneyFlowTemporeRequest\x1a%.taskmanager.MoneyFlowTemporeResponse\x12J\n\tRendement\x12\x1d.taskmanager.RendementRequest\x1a\x1e.taskmanager.RendementResponse\x12;\n\x04Vwap\x12\x18.taskmanager.VwapRequest\x1a\x19.taskmanager.VwapResponse\x12;\n\x04Twap\x12\x18.taskmanager.TwapRequest\x1a\x19.taskmanager.TwapResponseb\x06proto3')



_MONEYFLOWCLASSIQUEREQUEST = DESCRIPTOR.message_types_by_name['MoneyFlowClassiqueRequest']
_MONEYFLOWCLASSIQUERESPONSE = DESCRIPTOR.message_types_by_name['MoneyFlowClassiqueResponse']
_MONEYFLOWTEMPOREREQUEST = DESCRIPTOR.message_types_by_name['MoneyFlowTemporeRequest']
_MONEYFLOWTEMPORERESPONSE = DESCRIPTOR.message_types_by_name['MoneyFlowTemporeResponse']
_RENDEMENTREQUEST = DESCRIPTOR.message_types_by_name['RendementRequest']
_RENDEMENTRESPONSE = DESCRIPTOR.message_types_by_name['RendementResponse']
_VWAPREQUEST = DESCRIPTOR.message_types_by_name['VwapRequest']
_VWAPRESPONSE = DESCRIPTOR.message_types_by_name['VwapResponse']
_TWAPREQUEST = DESCRIPTOR.message_types_by_name['TwapRequest']
_TWAPRESPONSE = DESCRIPTOR.message_types_by_name['TwapResponse']
MoneyFlowClassiqueRequest = _reflection.GeneratedProtocolMessageType('MoneyFlowClassiqueRequest', (_message.Message,), {
  'DESCRIPTOR' : _MONEYFLOWCLASSIQUEREQUEST,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.MoneyFlowClassiqueRequest)
  })
_sym_db.RegisterMessage(MoneyFlowClassiqueRequest)

MoneyFlowClassiqueResponse = _reflection.GeneratedProtocolMessageType('MoneyFlowClassiqueResponse', (_message.Message,), {
  'DESCRIPTOR' : _MONEYFLOWCLASSIQUERESPONSE,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.MoneyFlowClassiqueResponse)
  })
_sym_db.RegisterMessage(MoneyFlowClassiqueResponse)

MoneyFlowTemporeRequest = _reflection.GeneratedProtocolMessageType('MoneyFlowTemporeRequest', (_message.Message,), {
  'DESCRIPTOR' : _MONEYFLOWTEMPOREREQUEST,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.MoneyFlowTemporeRequest)
  })
_sym_db.RegisterMessage(MoneyFlowTemporeRequest)

MoneyFlowTemporeResponse = _reflection.GeneratedProtocolMessageType('MoneyFlowTemporeResponse', (_message.Message,), {
  'DESCRIPTOR' : _MONEYFLOWTEMPORERESPONSE,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.MoneyFlowTemporeResponse)
  })
_sym_db.RegisterMessage(MoneyFlowTemporeResponse)

RendementRequest = _reflection.GeneratedProtocolMessageType('RendementRequest', (_message.Message,), {
  'DESCRIPTOR' : _RENDEMENTREQUEST,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.RendementRequest)
  })
_sym_db.RegisterMessage(RendementRequest)

RendementResponse = _reflection.GeneratedProtocolMessageType('RendementResponse', (_message.Message,), {
  'DESCRIPTOR' : _RENDEMENTRESPONSE,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.RendementResponse)
  })
_sym_db.RegisterMessage(RendementResponse)

VwapRequest = _reflection.GeneratedProtocolMessageType('VwapRequest', (_message.Message,), {
  'DESCRIPTOR' : _VWAPREQUEST,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.VwapRequest)
  })
_sym_db.RegisterMessage(VwapRequest)

VwapResponse = _reflection.GeneratedProtocolMessageType('VwapResponse', (_message.Message,), {
  'DESCRIPTOR' : _VWAPRESPONSE,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.VwapResponse)
  })
_sym_db.RegisterMessage(VwapResponse)

TwapRequest = _reflection.GeneratedProtocolMessageType('TwapRequest', (_message.Message,), {
  'DESCRIPTOR' : _TWAPREQUEST,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.TwapRequest)
  })
_sym_db.RegisterMessage(TwapRequest)

TwapResponse = _reflection.GeneratedProtocolMessageType('TwapResponse', (_message.Message,), {
  'DESCRIPTOR' : _TWAPRESPONSE,
  '__module__' : 'taskmanager_pb2'
  # @@protoc_insertion_point(class_scope:taskmanager.TwapResponse)
  })
_sym_db.RegisterMessage(TwapResponse)

_TASKSERVICE = DESCRIPTOR.services_by_name['TaskService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MONEYFLOWCLASSIQUEREQUEST._serialized_start=28
  _MONEYFLOWCLASSIQUEREQUEST._serialized_end=55
  _MONEYFLOWCLASSIQUERESPONSE._serialized_start=57
  _MONEYFLOWCLASSIQUERESPONSE._serialized_end=100
  _MONEYFLOWTEMPOREREQUEST._serialized_start=102
  _MONEYFLOWTEMPOREREQUEST._serialized_end=127
  _MONEYFLOWTEMPORERESPONSE._serialized_start=129
  _MONEYFLOWTEMPORERESPONSE._serialized_end=170
  _RENDEMENTREQUEST._serialized_start=172
  _RENDEMENTREQUEST._serialized_end=190
  _RENDEMENTRESPONSE._serialized_start=192
  _RENDEMENTRESPONSE._serialized_end=226
  _VWAPREQUEST._serialized_start=228
  _VWAPREQUEST._serialized_end=241
  _VWAPRESPONSE._serialized_start=243
  _VWAPRESPONSE._serialized_end=272
  _TWAPREQUEST._serialized_start=274
  _TWAPREQUEST._serialized_end=287
  _TWAPRESPONSE._serialized_start=289
  _TWAPRESPONSE._serialized_end=318
  _TASKSERVICE._serialized_start=321
  _TASKSERVICE._serialized_end=732
# @@protoc_insertion_point(module_scope)
