# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import taskmanager_pb2 as taskmanager__pb2


class TaskServiceStub(object):
    """Le service de gestion de tâches
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTask = channel.unary_unary(
                '/taskmanager.TaskService/AddTask',
                request_serializer=taskmanager__pb2.AddTaskRequest.SerializeToString,
                response_deserializer=taskmanager__pb2.AddTaskResponse.FromString,
                )
        self.ListTasks = channel.unary_unary(
                '/taskmanager.TaskService/ListTasks',
                request_serializer=taskmanager__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=taskmanager__pb2.ListTasksResponse.FromString,
                )


class TaskServiceServicer(object):
    """Le service de gestion de tâches
    """

    def AddTask(self, request, context):
        """Ajoute une nouvelle tâche
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Liste toutes les tâches
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTask,
                    request_deserializer=taskmanager__pb2.AddTaskRequest.FromString,
                    response_serializer=taskmanager__pb2.AddTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=taskmanager__pb2.ListTasksRequest.FromString,
                    response_serializer=taskmanager__pb2.ListTasksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskmanager.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Le service de gestion de tâches
    """

    @staticmethod
    def AddTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/taskmanager.TaskService/AddTask',
            taskmanager__pb2.AddTaskRequest.SerializeToString,
            taskmanager__pb2.AddTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/taskmanager.TaskService/ListTasks',
            taskmanager__pb2.ListTasksRequest.SerializeToString,
            taskmanager__pb2.ListTasksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
